# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QMainWindow, QPushButton, QSizePolicy, QStatusBar,
    QToolButton, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 555)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame_2 = QFrame(self.centralwidget)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(10, 60, 271, 471))
        self.frame_2.setFrameShape(QFrame.Shape.Box)
        self.frame_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_title_channel = QLabel(self.frame_2)
        self.lbl_title_channel.setObjectName(u"lbl_title_channel")
        self.lbl_title_channel.setGeometry(QRect(11, 8, 221, 31))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        font.setPointSize(11)
        font.setBold(True)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.lbl_title_channel.setFont(font)
        self.lbl_title_channel.setAutoFillBackground(True)
        self.lbl_title_channel.setStyleSheet(u"")
        self.lbl_title_channel.setFrameShape(QFrame.Shape.Box)
        self.lbl_title_channel.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_title_channel.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_001 = QLabel(self.frame_2)
        self.lbl_001.setObjectName(u"lbl_001")
        self.lbl_001.setGeometry(QRect(10, 60, 111, 16))
        font1 = QFont()
        font1.setPointSize(10)
        font1.setBold(True)
        self.lbl_001.setFont(font1)
        self.lbl_001.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_001 = QLineEdit(self.frame_2)
        self.edit_001.setObjectName(u"edit_001")
        self.edit_001.setGeometry(QRect(130, 57, 113, 22))
        self.edit_001.setFont(font1)
        self.edit_001.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_002 = QLabel(self.frame_2)
        self.lbl_002.setObjectName(u"lbl_002")
        self.lbl_002.setGeometry(QRect(10, 88, 111, 16))
        self.lbl_002.setFont(font1)
        self.lbl_002.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_002 = QLineEdit(self.frame_2)
        self.edit_002.setObjectName(u"edit_002")
        self.edit_002.setEnabled(True)
        self.edit_002.setGeometry(QRect(130, 87, 113, 22))
        self.edit_002.setFont(font1)
        self.edit_002.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_002.setReadOnly(True)
        self.lbl_003 = QLabel(self.frame_2)
        self.lbl_003.setObjectName(u"lbl_003")
        self.lbl_003.setGeometry(QRect(10, 118, 111, 16))
        self.lbl_003.setFont(font1)
        self.lbl_003.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_003 = QLineEdit(self.frame_2)
        self.edit_003.setObjectName(u"edit_003")
        self.edit_003.setGeometry(QRect(130, 117, 113, 22))
        self.edit_003.setFont(font1)
        self.edit_003.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_003.setReadOnly(True)
        self.lbl_004 = QLabel(self.frame_2)
        self.lbl_004.setObjectName(u"lbl_004")
        self.lbl_004.setGeometry(QRect(10, 148, 111, 16))
        self.lbl_004.setFont(font1)
        self.lbl_004.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_004 = QLineEdit(self.frame_2)
        self.edit_004.setObjectName(u"edit_004")
        self.edit_004.setGeometry(QRect(130, 147, 113, 22))
        self.edit_004.setFont(font1)
        self.edit_004.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_004.setReadOnly(True)
        self.lbl_005 = QLabel(self.frame_2)
        self.lbl_005.setObjectName(u"lbl_005")
        self.lbl_005.setGeometry(QRect(10, 178, 111, 16))
        self.lbl_005.setFont(font1)
        self.lbl_005.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_005 = QLineEdit(self.frame_2)
        self.edit_005.setObjectName(u"edit_005")
        self.edit_005.setGeometry(QRect(130, 177, 113, 22))
        self.edit_005.setFont(font1)
        self.edit_005.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_005.setReadOnly(True)
        self.lbl_006 = QLabel(self.frame_2)
        self.lbl_006.setObjectName(u"lbl_006")
        self.lbl_006.setGeometry(QRect(10, 208, 111, 16))
        self.lbl_006.setFont(font1)
        self.lbl_006.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_006 = QLineEdit(self.frame_2)
        self.edit_006.setObjectName(u"edit_006")
        self.edit_006.setGeometry(QRect(130, 207, 113, 22))
        self.edit_006.setFont(font1)
        self.edit_006.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_006.setReadOnly(True)
        self.lbl_007 = QLabel(self.frame_2)
        self.lbl_007.setObjectName(u"lbl_007")
        self.lbl_007.setGeometry(QRect(10, 238, 111, 16))
        self.lbl_007.setFont(font1)
        self.lbl_007.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_009 = QLabel(self.frame_2)
        self.lbl_009.setObjectName(u"lbl_009")
        self.lbl_009.setGeometry(QRect(10, 298, 111, 16))
        self.lbl_009.setFont(font1)
        self.lbl_009.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_010 = QLineEdit(self.frame_2)
        self.edit_010.setObjectName(u"edit_010")
        self.edit_010.setGeometry(QRect(130, 327, 113, 22))
        self.edit_010.setFont(font1)
        self.edit_010.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_010.setReadOnly(True)
        self.edit_011 = QLineEdit(self.frame_2)
        self.edit_011.setObjectName(u"edit_011")
        self.edit_011.setGeometry(QRect(130, 357, 113, 22))
        self.edit_011.setFont(font1)
        self.edit_011.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_011.setReadOnly(True)
        self.edit_007 = QLineEdit(self.frame_2)
        self.edit_007.setObjectName(u"edit_007")
        self.edit_007.setGeometry(QRect(130, 237, 113, 22))
        self.edit_007.setFont(font1)
        self.edit_007.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_007.setReadOnly(True)
        self.lbl_011 = QLabel(self.frame_2)
        self.lbl_011.setObjectName(u"lbl_011")
        self.lbl_011.setGeometry(QRect(10, 358, 111, 16))
        self.lbl_011.setFont(font1)
        self.lbl_011.setStyleSheet(u"")
        self.lbl_011.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_010 = QLabel(self.frame_2)
        self.lbl_010.setObjectName(u"lbl_010")
        self.lbl_010.setGeometry(QRect(10, 328, 111, 16))
        self.lbl_010.setFont(font1)
        self.lbl_010.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_012 = QLabel(self.frame_2)
        self.lbl_012.setObjectName(u"lbl_012")
        self.lbl_012.setGeometry(QRect(10, 388, 111, 16))
        self.lbl_012.setFont(font1)
        self.lbl_012.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_009 = QLineEdit(self.frame_2)
        self.edit_009.setObjectName(u"edit_009")
        self.edit_009.setGeometry(QRect(130, 297, 113, 22))
        self.edit_009.setFont(font1)
        self.edit_009.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_009.setReadOnly(True)
        self.lbl_008 = QLabel(self.frame_2)
        self.lbl_008.setObjectName(u"lbl_008")
        self.lbl_008.setGeometry(QRect(10, 268, 111, 16))
        self.lbl_008.setFont(font1)
        self.lbl_008.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_008 = QLineEdit(self.frame_2)
        self.edit_008.setObjectName(u"edit_008")
        self.edit_008.setGeometry(QRect(130, 267, 113, 22))
        self.edit_008.setFont(font1)
        self.edit_008.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_008.setReadOnly(True)
        self.edit_012 = QLineEdit(self.frame_2)
        self.edit_012.setObjectName(u"edit_012")
        self.edit_012.setGeometry(QRect(130, 387, 113, 22))
        self.edit_012.setFont(font1)
        self.edit_012.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_012.setReadOnly(True)
        self.btn_start_test = QPushButton(self.frame_2)
        self.btn_start_test.setObjectName(u"btn_start_test")
        self.btn_start_test.setEnabled(False)
        self.btn_start_test.setGeometry(QRect(20, 430, 231, 24))
        self.tbtn_settings_channel_01 = QToolButton(self.frame_2)
        self.tbtn_settings_channel_01.setObjectName(u"tbtn_settings_channel_01")
        self.tbtn_settings_channel_01.setGeometry(QRect(235, 8, 31, 31))
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(10, 9, 781, 41))
        self.frame.setMinimumSize(QSize(0, 20))
        self.frame.setFrameShape(QFrame.Shape.Box)
        self.frame.setFrameShadow(QFrame.Shadow.Sunken)
        self.btn_connect = QPushButton(self.frame)
        self.btn_connect.setObjectName(u"btn_connect")
        self.btn_connect.setGeometry(QRect(10, 10, 131, 24))
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(185, 12, 371, 20))
        self.label_2 = QLabel(self.frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(600, 12, 141, 20))
        self.tbtn_settings = QToolButton(self.frame)
        self.tbtn_settings.setObjectName(u"tbtn_settings")
        self.tbtn_settings.setGeometry(QRect(744, 5, 31, 31))
        self.tbtn_add_channel = QToolButton(self.centralwidget)
        self.tbtn_add_channel.setObjectName(u"tbtn_add_channel")
        self.tbtn_add_channel.setGeometry(QRect(290, 500, 31, 31))
        font2 = QFont()
        font2.setPointSize(12)
        font2.setBold(True)
        self.tbtn_add_channel.setFont(font2)
        self.tbtn_add_channel.setArrowType(Qt.ArrowType.NoArrow)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setToolTipDuration(-1)
        self.statusBar.setSizeGripEnabled(True)
        MainWindow.setStatusBar(self.statusBar)
#if QT_CONFIG(shortcut)
#endif // QT_CONFIG(shortcut)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
#if QT_CONFIG(accessibility)
        MainWindow.setAccessibleDescription("")
#endif // QT_CONFIG(accessibility)
        self.lbl_title_channel.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0430\u043d\u0430\u043b 1", None))
        self.lbl_001.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u043c\u0435\u0440 \u0410\u041a\u0411", None))
        self.edit_001.setText(QCoreApplication.translate("MainWindow", u"AKB-0000", None))
        self.lbl_002.setText(QCoreApplication.translate("MainWindow", u"\u0421\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u0435", None))
        self.edit_002.setText(QCoreApplication.translate("MainWindow", u"\u0411\u0435\u0437\u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435", None))
        self.lbl_003.setText(QCoreApplication.translate("MainWindow", u"U \u043d\u0430\u0447", None))
        self.edit_003.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_004.setText(QCoreApplication.translate("MainWindow", u"U \u0442\u0435\u043a", None))
        self.edit_004.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_005.setText(QCoreApplication.translate("MainWindow", u"I \u0442\u0435\u043a", None))
        self.edit_005.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_006.setText(QCoreApplication.translate("MainWindow", u"P \u0442\u0435\u043a", None))
        self.edit_006.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_007.setText(QCoreApplication.translate("MainWindow", u"C \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_009.setText(QCoreApplication.translate("MainWindow", u"C \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.edit_010.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_011.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_007.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_011.setText(QCoreApplication.translate("MainWindow", u"C \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_010.setText(QCoreApplication.translate("MainWindow", u"W \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.lbl_012.setText(QCoreApplication.translate("MainWindow", u"W \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_009.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_008.setText(QCoreApplication.translate("MainWindow", u"W \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_008.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_012.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.btn_start_test.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u0443\u0441\u043a \u0442\u0435\u0441\u0442\u0430", None))
#if QT_CONFIG(tooltip)
        self.tbtn_settings_channel_01.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbtn_settings_channel_01.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043a\u0430\u043d\u0430\u043b\u0430", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_settings_channel_01.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.btn_connect.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u043a\u043b\u044e\u0447\u0438\u0442\u044c\u0441\u044f", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043e\u0448\u0438\u0431\u043e\u043a:", None))
#if QT_CONFIG(tooltip)
        self.tbtn_settings.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbtn_settings.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u044b", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_settings.setText(QCoreApplication.translate("MainWindow", u"...", None))
#if QT_CONFIG(tooltip)
        self.tbtn_add_channel.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbtn_add_channel.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u043a\u0430\u043d\u0430\u043b", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_add_channel.setText(QCoreApplication.translate("MainWindow", u"+", None))
#if QT_CONFIG(statustip)
        self.statusBar.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.statusBar.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
    # retranslateUi

