# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFrame, QLabel,
    QLineEdit, QMainWindow, QPushButton, QSizePolicy,
    QStatusBar, QToolButton, QWidget)
import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1130, 601)
        MainWindow.setMinimumSize(QSize(1130, 601))
        MainWindow.setMaximumSize(QSize(1130, 601))
        font = QFont()
        font.setPointSize(9)
        font.setBold(False)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/ICO/Charging24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"#edit_002, #edit_003, #edit_004, #edit_005, #edit_006, #edit_007,\n"
"#edit_008, #edit_009, #edit_010, #edit_011, #edit_012 {\n"
"	background-color: rgb(0, 0, 0);\n"
"	color: rgb(1, 255, 31);\n"
"}\n"
"#frm_back_ch_1, #frm_back_ch_2, #frm_back_ch_3, #frm_back_ch_4 {\n"
"	background-color: rgb(210, 210, 210);\n"
"}")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.frame_channel = QFrame(self.centralwidget)
        self.frame_channel.setObjectName(u"frame_channel")
        self.frame_channel.setEnabled(True)
        self.frame_channel.setGeometry(QRect(10, 60, 271, 521))
        self.frame_channel.setFrameShape(QFrame.Shape.Box)
        self.frame_channel.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_ico_channel_1 = QLabel(self.frame_channel)
        self.lbl_ico_channel_1.setObjectName(u"lbl_ico_channel_1")
        self.lbl_ico_channel_1.setGeometry(QRect(6, 6, 41, 41))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setStrikeOut(False)
        font1.setKerning(True)
        self.lbl_ico_channel_1.setFont(font1)
        self.lbl_ico_channel_1.setAutoFillBackground(False)
        self.lbl_ico_channel_1.setStyleSheet(u"")
        self.lbl_ico_channel_1.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_ico_channel_1.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_ico_channel_1.setTextFormat(Qt.TextFormat.AutoText)
        self.lbl_ico_channel_1.setPixmap(QPixmap(u":/ICO/N1_36.png"))
        self.lbl_ico_channel_1.setScaledContents(False)
        self.lbl_ico_channel_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_ico_channel_1.setOpenExternalLinks(False)
        self.lbl_ico_channel_1.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.lbl_001 = QLabel(self.frame_channel)
        self.lbl_001.setObjectName(u"lbl_001")
        self.lbl_001.setGeometry(QRect(10, 82, 88, 16))
        font2 = QFont()
        font2.setPointSize(10)
        font2.setBold(True)
        self.lbl_001.setFont(font2)
        self.lbl_001.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_001 = QLineEdit(self.frame_channel)
        self.edit_001.setObjectName(u"edit_001")
        self.edit_001.setGeometry(QRect(110, 75, 133, 28))
        self.edit_001.setFont(font2)
        self.edit_001.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_003 = QLabel(self.frame_channel)
        self.lbl_003.setObjectName(u"lbl_003")
        self.lbl_003.setGeometry(QRect(10, 131, 111, 16))
        self.lbl_003.setFont(font2)
        self.lbl_003.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_003 = QLineEdit(self.frame_channel)
        self.edit_003.setObjectName(u"edit_003")
        self.edit_003.setGeometry(QRect(130, 125, 113, 28))
        self.edit_003.setFont(font2)
        self.edit_003.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_003.setReadOnly(True)
        self.lbl_004 = QLabel(self.frame_channel)
        self.lbl_004.setObjectName(u"lbl_004")
        self.lbl_004.setGeometry(QRect(10, 165, 111, 16))
        self.lbl_004.setFont(font2)
        self.lbl_004.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_004 = QLineEdit(self.frame_channel)
        self.edit_004.setObjectName(u"edit_004")
        self.edit_004.setGeometry(QRect(130, 160, 113, 28))
        self.edit_004.setFont(font2)
        self.edit_004.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_004.setReadOnly(True)
        self.lbl_005 = QLabel(self.frame_channel)
        self.lbl_005.setObjectName(u"lbl_005")
        self.lbl_005.setGeometry(QRect(10, 200, 111, 16))
        self.lbl_005.setFont(font2)
        self.lbl_005.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_005 = QLineEdit(self.frame_channel)
        self.edit_005.setObjectName(u"edit_005")
        self.edit_005.setGeometry(QRect(130, 195, 113, 28))
        self.edit_005.setFont(font2)
        self.edit_005.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_005.setReadOnly(True)
        self.lbl_006 = QLabel(self.frame_channel)
        self.lbl_006.setObjectName(u"lbl_006")
        self.lbl_006.setGeometry(QRect(10, 235, 111, 16))
        self.lbl_006.setFont(font2)
        self.lbl_006.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_006 = QLineEdit(self.frame_channel)
        self.edit_006.setObjectName(u"edit_006")
        self.edit_006.setGeometry(QRect(130, 230, 113, 28))
        self.edit_006.setFont(font2)
        self.edit_006.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_006.setReadOnly(True)
        self.lbl_007 = QLabel(self.frame_channel)
        self.lbl_007.setObjectName(u"lbl_007")
        self.lbl_007.setGeometry(QRect(10, 270, 111, 16))
        self.lbl_007.setFont(font2)
        self.lbl_007.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_009 = QLabel(self.frame_channel)
        self.lbl_009.setObjectName(u"lbl_009")
        self.lbl_009.setGeometry(QRect(10, 340, 111, 16))
        self.lbl_009.setFont(font2)
        self.lbl_009.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_010 = QLineEdit(self.frame_channel)
        self.edit_010.setObjectName(u"edit_010")
        self.edit_010.setGeometry(QRect(130, 370, 113, 28))
        self.edit_010.setFont(font2)
        self.edit_010.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_010.setReadOnly(True)
        self.edit_011 = QLineEdit(self.frame_channel)
        self.edit_011.setObjectName(u"edit_011")
        self.edit_011.setGeometry(QRect(130, 406, 113, 28))
        self.edit_011.setFont(font2)
        self.edit_011.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_011.setReadOnly(True)
        self.edit_007 = QLineEdit(self.frame_channel)
        self.edit_007.setObjectName(u"edit_007")
        self.edit_007.setGeometry(QRect(130, 266, 113, 28))
        self.edit_007.setFont(font2)
        self.edit_007.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_007.setReadOnly(True)
        self.lbl_011 = QLabel(self.frame_channel)
        self.lbl_011.setObjectName(u"lbl_011")
        self.lbl_011.setGeometry(QRect(10, 410, 111, 16))
        self.lbl_011.setFont(font2)
        self.lbl_011.setStyleSheet(u"")
        self.lbl_011.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_010 = QLabel(self.frame_channel)
        self.lbl_010.setObjectName(u"lbl_010")
        self.lbl_010.setGeometry(QRect(10, 374, 111, 16))
        self.lbl_010.setFont(font2)
        self.lbl_010.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_012 = QLabel(self.frame_channel)
        self.lbl_012.setObjectName(u"lbl_012")
        self.lbl_012.setGeometry(QRect(10, 444, 111, 16))
        self.lbl_012.setFont(font2)
        self.lbl_012.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_009 = QLineEdit(self.frame_channel)
        self.edit_009.setObjectName(u"edit_009")
        self.edit_009.setGeometry(QRect(130, 336, 113, 28))
        self.edit_009.setFont(font2)
        self.edit_009.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_009.setReadOnly(True)
        self.lbl_008 = QLabel(self.frame_channel)
        self.lbl_008.setObjectName(u"lbl_008")
        self.lbl_008.setGeometry(QRect(10, 304, 111, 16))
        self.lbl_008.setFont(font2)
        self.lbl_008.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_008 = QLineEdit(self.frame_channel)
        self.edit_008.setObjectName(u"edit_008")
        self.edit_008.setGeometry(QRect(130, 300, 113, 28))
        self.edit_008.setFont(font2)
        self.edit_008.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_008.setReadOnly(True)
        self.edit_012 = QLineEdit(self.frame_channel)
        self.edit_012.setObjectName(u"edit_012")
        self.edit_012.setGeometry(QRect(130, 440, 113, 28))
        self.edit_012.setFont(font2)
        self.edit_012.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_012.setReadOnly(True)
        self.btn_start_test = QPushButton(self.frame_channel)
        self.btn_start_test.setObjectName(u"btn_start_test")
        self.btn_start_test.setEnabled(True)
        self.btn_start_test.setGeometry(QRect(20, 480, 231, 31))
        font3 = QFont()
        font3.setPointSize(10)
        self.btn_start_test.setFont(font3)
        icon1 = QIcon()
        icon1.addFile(u":/ICO/Zap24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_start_test.setIcon(icon1)
        self.tbtn_settings_channel_1 = QToolButton(self.frame_channel)
        self.tbtn_settings_channel_1.setObjectName(u"tbtn_settings_channel_1")
        self.tbtn_settings_channel_1.setGeometry(QRect(230, 10, 31, 31))
        self.tbtn_settings_channel_1.setAutoFillBackground(False)
        icon2 = QIcon()
        icon2.addFile(u":/ICO/Gear24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.tbtn_settings_channel_1.setIcon(icon2)
        self.lbl_satus_channel_1 = QLabel(self.frame_channel)
        self.lbl_satus_channel_1.setObjectName(u"lbl_satus_channel_1")
        self.lbl_satus_channel_1.setEnabled(True)
        self.lbl_satus_channel_1.setGeometry(QRect(50, 10, 171, 31))
        self.lbl_satus_channel_1.setFont(font1)
        self.lbl_satus_channel_1.setAutoFillBackground(False)
        self.lbl_satus_channel_1.setStyleSheet(u"")
        self.lbl_satus_channel_1.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_satus_channel_1.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_satus_channel_1.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.frm_back_ch_1 = QFrame(self.frame_channel)
        self.frm_back_ch_1.setObjectName(u"frm_back_ch_1")
        self.frm_back_ch_1.setGeometry(QRect(2, 2, 266, 48))
        self.frm_back_ch_1.setFrameShape(QFrame.Shape.Panel)
        self.frm_back_ch_1.setFrameShadow(QFrame.Shadow.Plain)
        self.frm_back_ch_1.raise_()
        self.lbl_ico_channel_1.raise_()
        self.lbl_001.raise_()
        self.edit_001.raise_()
        self.lbl_003.raise_()
        self.edit_003.raise_()
        self.lbl_004.raise_()
        self.edit_004.raise_()
        self.lbl_005.raise_()
        self.edit_005.raise_()
        self.lbl_006.raise_()
        self.edit_006.raise_()
        self.lbl_007.raise_()
        self.lbl_009.raise_()
        self.edit_010.raise_()
        self.edit_011.raise_()
        self.edit_007.raise_()
        self.lbl_011.raise_()
        self.lbl_010.raise_()
        self.lbl_012.raise_()
        self.edit_009.raise_()
        self.lbl_008.raise_()
        self.edit_008.raise_()
        self.edit_012.raise_()
        self.btn_start_test.raise_()
        self.tbtn_settings_channel_1.raise_()
        self.lbl_satus_channel_1.raise_()
        self.frame_top = QFrame(self.centralwidget)
        self.frame_top.setObjectName(u"frame_top")
        self.frame_top.setGeometry(QRect(10, 9, 1111, 47))
        self.frame_top.setMinimumSize(QSize(0, 20))
        self.frame_top.setFrameShape(QFrame.Shape.Box)
        self.frame_top.setFrameShadow(QFrame.Shadow.Sunken)
        self.btn_connect = QPushButton(self.frame_top)
        self.btn_connect.setObjectName(u"btn_connect")
        self.btn_connect.setGeometry(QRect(169, 8, 141, 31))
        self.btn_connect.setFont(font2)
        icon3 = QIcon()
        icon3.addFile(u":/ICO/Plug24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_connect.setIcon(icon3)
        self.lbl_messages = QLabel(self.frame_top)
        self.lbl_messages.setObjectName(u"lbl_messages")
        self.lbl_messages.setGeometry(QRect(319, 15, 541, 20))
        self.lbl_messages.setFont(font3)
        self.lbl_error = QLabel(self.frame_top)
        self.lbl_error.setObjectName(u"lbl_error")
        self.lbl_error.setGeometry(QRect(870, 15, 81, 20))
        self.lbl_error.setFont(font3)
        self.btn_logs = QPushButton(self.frame_top)
        self.btn_logs.setObjectName(u"btn_logs")
        self.btn_logs.setGeometry(QRect(961, 8, 141, 31))
        self.btn_logs.setFont(font3)
        icon4 = QIcon()
        icon4.addFile(u":/ICO/Log24.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.btn_logs.setIcon(icon4)
        self.btn_logs.setFlat(False)
        self.lbl_com_ports = QLabel(self.frame_top)
        self.lbl_com_ports.setObjectName(u"lbl_com_ports")
        self.lbl_com_ports.setGeometry(QRect(16, 13, 41, 20))
        self.lbl_com_ports.setFont(font2)
        self.list_com = QComboBox(self.frame_top)
        self.list_com.setObjectName(u"list_com")
        self.list_com.setGeometry(QRect(60, 9, 69, 29))
        self.tbtn_settings_com = QToolButton(self.frame_top)
        self.tbtn_settings_com.setObjectName(u"tbtn_settings_com")
        self.tbtn_settings_com.setGeometry(QRect(130, 8, 31, 31))
        self.tbtn_settings_com.setIcon(icon2)
        self.frame_channel_2 = QFrame(self.centralwidget)
        self.frame_channel_2.setObjectName(u"frame_channel_2")
        self.frame_channel_2.setEnabled(False)
        self.frame_channel_2.setGeometry(QRect(290, 60, 271, 521))
        self.frame_channel_2.setFrameShape(QFrame.Shape.Box)
        self.frame_channel_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_status_channel_2 = QLabel(self.frame_channel_2)
        self.lbl_status_channel_2.setObjectName(u"lbl_status_channel_2")
        self.lbl_status_channel_2.setGeometry(QRect(51, 10, 171, 31))
        self.lbl_status_channel_2.setFont(font1)
        self.lbl_status_channel_2.setAutoFillBackground(False)
        self.lbl_status_channel_2.setStyleSheet(u"")
        self.lbl_status_channel_2.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_status_channel_2.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_status_channel_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_2 = QLabel(self.frame_channel_2)
        self.lbl_2.setObjectName(u"lbl_2")
        self.lbl_2.setGeometry(QRect(10, 82, 88, 16))
        self.lbl_2.setFont(font2)
        self.lbl_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_2 = QLineEdit(self.frame_channel_2)
        self.edit_2.setObjectName(u"edit_2")
        self.edit_2.setGeometry(QRect(110, 75, 133, 28))
        self.edit_2.setFont(font2)
        self.edit_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_4 = QLabel(self.frame_channel_2)
        self.lbl_4.setObjectName(u"lbl_4")
        self.lbl_4.setGeometry(QRect(10, 131, 111, 16))
        self.lbl_4.setFont(font2)
        self.lbl_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_4 = QLineEdit(self.frame_channel_2)
        self.edit_4.setObjectName(u"edit_4")
        self.edit_4.setGeometry(QRect(130, 125, 113, 28))
        self.edit_4.setFont(font2)
        self.edit_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_4.setReadOnly(True)
        self.lbl_5 = QLabel(self.frame_channel_2)
        self.lbl_5.setObjectName(u"lbl_5")
        self.lbl_5.setGeometry(QRect(10, 165, 111, 16))
        self.lbl_5.setFont(font2)
        self.lbl_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_5 = QLineEdit(self.frame_channel_2)
        self.edit_5.setObjectName(u"edit_5")
        self.edit_5.setGeometry(QRect(130, 160, 113, 28))
        self.edit_5.setFont(font2)
        self.edit_5.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_5.setReadOnly(True)
        self.lbl_6 = QLabel(self.frame_channel_2)
        self.lbl_6.setObjectName(u"lbl_6")
        self.lbl_6.setGeometry(QRect(10, 200, 111, 16))
        self.lbl_6.setFont(font2)
        self.lbl_6.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_6 = QLineEdit(self.frame_channel_2)
        self.edit_6.setObjectName(u"edit_6")
        self.edit_6.setGeometry(QRect(130, 195, 113, 28))
        self.edit_6.setFont(font2)
        self.edit_6.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_6.setReadOnly(True)
        self.lbl_7 = QLabel(self.frame_channel_2)
        self.lbl_7.setObjectName(u"lbl_7")
        self.lbl_7.setGeometry(QRect(10, 235, 111, 16))
        self.lbl_7.setFont(font2)
        self.lbl_7.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_7 = QLineEdit(self.frame_channel_2)
        self.edit_7.setObjectName(u"edit_7")
        self.edit_7.setGeometry(QRect(130, 230, 113, 28))
        self.edit_7.setFont(font2)
        self.edit_7.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_7.setReadOnly(True)
        self.lbl_8 = QLabel(self.frame_channel_2)
        self.lbl_8.setObjectName(u"lbl_8")
        self.lbl_8.setGeometry(QRect(10, 270, 111, 16))
        self.lbl_8.setFont(font2)
        self.lbl_8.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_10 = QLabel(self.frame_channel_2)
        self.lbl_10.setObjectName(u"lbl_10")
        self.lbl_10.setGeometry(QRect(10, 340, 111, 16))
        self.lbl_10.setFont(font2)
        self.lbl_10.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_11 = QLineEdit(self.frame_channel_2)
        self.edit_11.setObjectName(u"edit_11")
        self.edit_11.setGeometry(QRect(130, 370, 113, 28))
        self.edit_11.setFont(font2)
        self.edit_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_11.setReadOnly(True)
        self.edit_12 = QLineEdit(self.frame_channel_2)
        self.edit_12.setObjectName(u"edit_12")
        self.edit_12.setGeometry(QRect(130, 406, 113, 28))
        self.edit_12.setFont(font2)
        self.edit_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_12.setReadOnly(True)
        self.edit_8 = QLineEdit(self.frame_channel_2)
        self.edit_8.setObjectName(u"edit_8")
        self.edit_8.setGeometry(QRect(130, 266, 113, 28))
        self.edit_8.setFont(font2)
        self.edit_8.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_8.setReadOnly(True)
        self.lbl_12 = QLabel(self.frame_channel_2)
        self.lbl_12.setObjectName(u"lbl_12")
        self.lbl_12.setGeometry(QRect(10, 410, 111, 16))
        self.lbl_12.setFont(font2)
        self.lbl_12.setStyleSheet(u"")
        self.lbl_12.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_11 = QLabel(self.frame_channel_2)
        self.lbl_11.setObjectName(u"lbl_11")
        self.lbl_11.setGeometry(QRect(10, 374, 111, 16))
        self.lbl_11.setFont(font2)
        self.lbl_11.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_13 = QLabel(self.frame_channel_2)
        self.lbl_13.setObjectName(u"lbl_13")
        self.lbl_13.setGeometry(QRect(10, 444, 111, 16))
        self.lbl_13.setFont(font2)
        self.lbl_13.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_10 = QLineEdit(self.frame_channel_2)
        self.edit_10.setObjectName(u"edit_10")
        self.edit_10.setGeometry(QRect(130, 336, 113, 28))
        self.edit_10.setFont(font2)
        self.edit_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_10.setReadOnly(True)
        self.lbl_9 = QLabel(self.frame_channel_2)
        self.lbl_9.setObjectName(u"lbl_9")
        self.lbl_9.setGeometry(QRect(10, 304, 111, 16))
        self.lbl_9.setFont(font2)
        self.lbl_9.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_9 = QLineEdit(self.frame_channel_2)
        self.edit_9.setObjectName(u"edit_9")
        self.edit_9.setGeometry(QRect(130, 300, 113, 28))
        self.edit_9.setFont(font2)
        self.edit_9.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_9.setReadOnly(True)
        self.edit_13 = QLineEdit(self.frame_channel_2)
        self.edit_13.setObjectName(u"edit_13")
        self.edit_13.setGeometry(QRect(130, 440, 113, 28))
        self.edit_13.setFont(font2)
        self.edit_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_13.setReadOnly(True)
        self.btn_start_test_2 = QPushButton(self.frame_channel_2)
        self.btn_start_test_2.setObjectName(u"btn_start_test_2")
        self.btn_start_test_2.setEnabled(False)
        self.btn_start_test_2.setGeometry(QRect(20, 480, 231, 31))
        self.btn_start_test_2.setFont(font3)
        self.btn_start_test_2.setIcon(icon1)
        self.tbtn_settings_channel_2 = QToolButton(self.frame_channel_2)
        self.tbtn_settings_channel_2.setObjectName(u"tbtn_settings_channel_2")
        self.tbtn_settings_channel_2.setGeometry(QRect(230, 10, 31, 31))
        self.tbtn_settings_channel_2.setIcon(icon2)
        self.lbl_ico_channel_2 = QLabel(self.frame_channel_2)
        self.lbl_ico_channel_2.setObjectName(u"lbl_ico_channel_2")
        self.lbl_ico_channel_2.setGeometry(QRect(6, 6, 41, 41))
        self.lbl_ico_channel_2.setFont(font1)
        self.lbl_ico_channel_2.setAutoFillBackground(False)
        self.lbl_ico_channel_2.setStyleSheet(u"")
        self.lbl_ico_channel_2.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_ico_channel_2.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_ico_channel_2.setTextFormat(Qt.TextFormat.AutoText)
        self.lbl_ico_channel_2.setPixmap(QPixmap(u":/ICO/N2_36.png"))
        self.lbl_ico_channel_2.setScaledContents(False)
        self.lbl_ico_channel_2.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_ico_channel_2.setOpenExternalLinks(False)
        self.lbl_ico_channel_2.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.frm_back_ch_2 = QFrame(self.frame_channel_2)
        self.frm_back_ch_2.setObjectName(u"frm_back_ch_2")
        self.frm_back_ch_2.setGeometry(QRect(2, 2, 266, 48))
        self.frm_back_ch_2.setFrameShape(QFrame.Shape.Panel)
        self.frm_back_ch_2.setFrameShadow(QFrame.Shadow.Plain)
        self.frm_back_ch_2.raise_()
        self.lbl_status_channel_2.raise_()
        self.lbl_2.raise_()
        self.edit_2.raise_()
        self.lbl_4.raise_()
        self.edit_4.raise_()
        self.lbl_5.raise_()
        self.edit_5.raise_()
        self.lbl_6.raise_()
        self.edit_6.raise_()
        self.lbl_7.raise_()
        self.edit_7.raise_()
        self.lbl_8.raise_()
        self.lbl_10.raise_()
        self.edit_11.raise_()
        self.edit_12.raise_()
        self.edit_8.raise_()
        self.lbl_12.raise_()
        self.lbl_11.raise_()
        self.lbl_13.raise_()
        self.edit_10.raise_()
        self.lbl_9.raise_()
        self.edit_9.raise_()
        self.edit_13.raise_()
        self.btn_start_test_2.raise_()
        self.tbtn_settings_channel_2.raise_()
        self.lbl_ico_channel_2.raise_()
        self.frame_channel_3 = QFrame(self.centralwidget)
        self.frame_channel_3.setObjectName(u"frame_channel_3")
        self.frame_channel_3.setEnabled(False)
        self.frame_channel_3.setGeometry(QRect(570, 60, 271, 521))
        self.frame_channel_3.setFrameShape(QFrame.Shape.Box)
        self.frame_channel_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_satus_channel_3 = QLabel(self.frame_channel_3)
        self.lbl_satus_channel_3.setObjectName(u"lbl_satus_channel_3")
        self.lbl_satus_channel_3.setGeometry(QRect(51, 10, 171, 31))
        self.lbl_satus_channel_3.setFont(font1)
        self.lbl_satus_channel_3.setAutoFillBackground(False)
        self.lbl_satus_channel_3.setStyleSheet(u"")
        self.lbl_satus_channel_3.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_satus_channel_3.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_satus_channel_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_14 = QLabel(self.frame_channel_3)
        self.lbl_14.setObjectName(u"lbl_14")
        self.lbl_14.setGeometry(QRect(10, 82, 88, 16))
        self.lbl_14.setFont(font2)
        self.lbl_14.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_14 = QLineEdit(self.frame_channel_3)
        self.edit_14.setObjectName(u"edit_14")
        self.edit_14.setGeometry(QRect(110, 75, 133, 28))
        self.edit_14.setFont(font2)
        self.edit_14.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_16 = QLabel(self.frame_channel_3)
        self.lbl_16.setObjectName(u"lbl_16")
        self.lbl_16.setGeometry(QRect(10, 131, 111, 16))
        self.lbl_16.setFont(font2)
        self.lbl_16.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_16 = QLineEdit(self.frame_channel_3)
        self.edit_16.setObjectName(u"edit_16")
        self.edit_16.setGeometry(QRect(130, 125, 113, 28))
        self.edit_16.setFont(font2)
        self.edit_16.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_16.setReadOnly(True)
        self.lbl_17 = QLabel(self.frame_channel_3)
        self.lbl_17.setObjectName(u"lbl_17")
        self.lbl_17.setGeometry(QRect(10, 165, 111, 16))
        self.lbl_17.setFont(font2)
        self.lbl_17.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_17 = QLineEdit(self.frame_channel_3)
        self.edit_17.setObjectName(u"edit_17")
        self.edit_17.setGeometry(QRect(130, 160, 113, 28))
        self.edit_17.setFont(font2)
        self.edit_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_17.setReadOnly(True)
        self.lbl_18 = QLabel(self.frame_channel_3)
        self.lbl_18.setObjectName(u"lbl_18")
        self.lbl_18.setGeometry(QRect(10, 200, 111, 16))
        self.lbl_18.setFont(font2)
        self.lbl_18.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_18 = QLineEdit(self.frame_channel_3)
        self.edit_18.setObjectName(u"edit_18")
        self.edit_18.setGeometry(QRect(130, 195, 113, 28))
        self.edit_18.setFont(font2)
        self.edit_18.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_18.setReadOnly(True)
        self.lbl_19 = QLabel(self.frame_channel_3)
        self.lbl_19.setObjectName(u"lbl_19")
        self.lbl_19.setGeometry(QRect(10, 235, 111, 16))
        self.lbl_19.setFont(font2)
        self.lbl_19.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_19 = QLineEdit(self.frame_channel_3)
        self.edit_19.setObjectName(u"edit_19")
        self.edit_19.setGeometry(QRect(130, 230, 113, 28))
        self.edit_19.setFont(font2)
        self.edit_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_19.setReadOnly(True)
        self.lbl_20 = QLabel(self.frame_channel_3)
        self.lbl_20.setObjectName(u"lbl_20")
        self.lbl_20.setGeometry(QRect(10, 270, 111, 16))
        self.lbl_20.setFont(font2)
        self.lbl_20.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_21 = QLabel(self.frame_channel_3)
        self.lbl_21.setObjectName(u"lbl_21")
        self.lbl_21.setGeometry(QRect(10, 340, 111, 16))
        self.lbl_21.setFont(font2)
        self.lbl_21.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_20 = QLineEdit(self.frame_channel_3)
        self.edit_20.setObjectName(u"edit_20")
        self.edit_20.setGeometry(QRect(130, 370, 113, 28))
        self.edit_20.setFont(font2)
        self.edit_20.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_20.setReadOnly(True)
        self.edit_21 = QLineEdit(self.frame_channel_3)
        self.edit_21.setObjectName(u"edit_21")
        self.edit_21.setGeometry(QRect(130, 406, 113, 28))
        self.edit_21.setFont(font2)
        self.edit_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_21.setReadOnly(True)
        self.edit_22 = QLineEdit(self.frame_channel_3)
        self.edit_22.setObjectName(u"edit_22")
        self.edit_22.setGeometry(QRect(130, 266, 113, 28))
        self.edit_22.setFont(font2)
        self.edit_22.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_22.setReadOnly(True)
        self.lbl_22 = QLabel(self.frame_channel_3)
        self.lbl_22.setObjectName(u"lbl_22")
        self.lbl_22.setGeometry(QRect(10, 410, 111, 16))
        self.lbl_22.setFont(font2)
        self.lbl_22.setStyleSheet(u"")
        self.lbl_22.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_23 = QLabel(self.frame_channel_3)
        self.lbl_23.setObjectName(u"lbl_23")
        self.lbl_23.setGeometry(QRect(10, 374, 111, 16))
        self.lbl_23.setFont(font2)
        self.lbl_23.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_24 = QLabel(self.frame_channel_3)
        self.lbl_24.setObjectName(u"lbl_24")
        self.lbl_24.setGeometry(QRect(10, 444, 111, 16))
        self.lbl_24.setFont(font2)
        self.lbl_24.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_23 = QLineEdit(self.frame_channel_3)
        self.edit_23.setObjectName(u"edit_23")
        self.edit_23.setGeometry(QRect(130, 336, 113, 28))
        self.edit_23.setFont(font2)
        self.edit_23.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_23.setReadOnly(True)
        self.lbl_25 = QLabel(self.frame_channel_3)
        self.lbl_25.setObjectName(u"lbl_25")
        self.lbl_25.setGeometry(QRect(10, 304, 111, 16))
        self.lbl_25.setFont(font2)
        self.lbl_25.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_24 = QLineEdit(self.frame_channel_3)
        self.edit_24.setObjectName(u"edit_24")
        self.edit_24.setGeometry(QRect(130, 300, 113, 28))
        self.edit_24.setFont(font2)
        self.edit_24.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_24.setReadOnly(True)
        self.edit_25 = QLineEdit(self.frame_channel_3)
        self.edit_25.setObjectName(u"edit_25")
        self.edit_25.setGeometry(QRect(130, 440, 113, 28))
        self.edit_25.setFont(font2)
        self.edit_25.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_25.setReadOnly(True)
        self.btn_start_test_3 = QPushButton(self.frame_channel_3)
        self.btn_start_test_3.setObjectName(u"btn_start_test_3")
        self.btn_start_test_3.setEnabled(False)
        self.btn_start_test_3.setGeometry(QRect(20, 480, 231, 31))
        self.btn_start_test_3.setFont(font3)
        self.btn_start_test_3.setIcon(icon1)
        self.tbtn_settings_channel_3 = QToolButton(self.frame_channel_3)
        self.tbtn_settings_channel_3.setObjectName(u"tbtn_settings_channel_3")
        self.tbtn_settings_channel_3.setGeometry(QRect(230, 10, 31, 31))
        self.tbtn_settings_channel_3.setIcon(icon2)
        self.lbl_ico_channel_3 = QLabel(self.frame_channel_3)
        self.lbl_ico_channel_3.setObjectName(u"lbl_ico_channel_3")
        self.lbl_ico_channel_3.setGeometry(QRect(6, 6, 41, 41))
        self.lbl_ico_channel_3.setFont(font1)
        self.lbl_ico_channel_3.setAutoFillBackground(False)
        self.lbl_ico_channel_3.setStyleSheet(u"")
        self.lbl_ico_channel_3.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_ico_channel_3.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_ico_channel_3.setTextFormat(Qt.TextFormat.AutoText)
        self.lbl_ico_channel_3.setPixmap(QPixmap(u":/ICO/N3_36.png"))
        self.lbl_ico_channel_3.setScaledContents(False)
        self.lbl_ico_channel_3.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_ico_channel_3.setOpenExternalLinks(False)
        self.lbl_ico_channel_3.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.frm_back_ch_3 = QFrame(self.frame_channel_3)
        self.frm_back_ch_3.setObjectName(u"frm_back_ch_3")
        self.frm_back_ch_3.setGeometry(QRect(2, 2, 266, 48))
        self.frm_back_ch_3.setFrameShape(QFrame.Shape.Panel)
        self.frm_back_ch_3.setFrameShadow(QFrame.Shadow.Plain)
        self.frm_back_ch_3.raise_()
        self.lbl_satus_channel_3.raise_()
        self.lbl_14.raise_()
        self.edit_14.raise_()
        self.lbl_16.raise_()
        self.edit_16.raise_()
        self.lbl_17.raise_()
        self.edit_17.raise_()
        self.lbl_18.raise_()
        self.edit_18.raise_()
        self.lbl_19.raise_()
        self.edit_19.raise_()
        self.lbl_20.raise_()
        self.lbl_21.raise_()
        self.edit_20.raise_()
        self.edit_21.raise_()
        self.edit_22.raise_()
        self.lbl_22.raise_()
        self.lbl_23.raise_()
        self.lbl_24.raise_()
        self.edit_23.raise_()
        self.lbl_25.raise_()
        self.edit_24.raise_()
        self.edit_25.raise_()
        self.btn_start_test_3.raise_()
        self.tbtn_settings_channel_3.raise_()
        self.lbl_ico_channel_3.raise_()
        self.frame_channel_4 = QFrame(self.centralwidget)
        self.frame_channel_4.setObjectName(u"frame_channel_4")
        self.frame_channel_4.setEnabled(False)
        self.frame_channel_4.setGeometry(QRect(850, 60, 271, 521))
        self.frame_channel_4.setFrameShape(QFrame.Shape.Box)
        self.frame_channel_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_status_channel_4 = QLabel(self.frame_channel_4)
        self.lbl_status_channel_4.setObjectName(u"lbl_status_channel_4")
        self.lbl_status_channel_4.setGeometry(QRect(51, 10, 171, 31))
        self.lbl_status_channel_4.setFont(font1)
        self.lbl_status_channel_4.setAutoFillBackground(False)
        self.lbl_status_channel_4.setStyleSheet(u"")
        self.lbl_status_channel_4.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_status_channel_4.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_status_channel_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_26 = QLabel(self.frame_channel_4)
        self.lbl_26.setObjectName(u"lbl_26")
        self.lbl_26.setGeometry(QRect(10, 82, 88, 16))
        self.lbl_26.setFont(font2)
        self.lbl_26.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_26 = QLineEdit(self.frame_channel_4)
        self.edit_26.setObjectName(u"edit_26")
        self.edit_26.setGeometry(QRect(110, 75, 133, 28))
        self.edit_26.setFont(font2)
        self.edit_26.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_28 = QLabel(self.frame_channel_4)
        self.lbl_28.setObjectName(u"lbl_28")
        self.lbl_28.setGeometry(QRect(10, 131, 111, 16))
        self.lbl_28.setFont(font2)
        self.lbl_28.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_28 = QLineEdit(self.frame_channel_4)
        self.edit_28.setObjectName(u"edit_28")
        self.edit_28.setGeometry(QRect(130, 125, 113, 28))
        self.edit_28.setFont(font2)
        self.edit_28.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_28.setReadOnly(True)
        self.lbl_29 = QLabel(self.frame_channel_4)
        self.lbl_29.setObjectName(u"lbl_29")
        self.lbl_29.setGeometry(QRect(10, 165, 111, 16))
        self.lbl_29.setFont(font2)
        self.lbl_29.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_29 = QLineEdit(self.frame_channel_4)
        self.edit_29.setObjectName(u"edit_29")
        self.edit_29.setGeometry(QRect(130, 160, 113, 28))
        self.edit_29.setFont(font2)
        self.edit_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_29.setReadOnly(True)
        self.lbl_30 = QLabel(self.frame_channel_4)
        self.lbl_30.setObjectName(u"lbl_30")
        self.lbl_30.setGeometry(QRect(10, 200, 111, 16))
        self.lbl_30.setFont(font2)
        self.lbl_30.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_30 = QLineEdit(self.frame_channel_4)
        self.edit_30.setObjectName(u"edit_30")
        self.edit_30.setGeometry(QRect(130, 195, 113, 28))
        self.edit_30.setFont(font2)
        self.edit_30.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_30.setReadOnly(True)
        self.lbl_31 = QLabel(self.frame_channel_4)
        self.lbl_31.setObjectName(u"lbl_31")
        self.lbl_31.setGeometry(QRect(10, 235, 111, 16))
        self.lbl_31.setFont(font2)
        self.lbl_31.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_31 = QLineEdit(self.frame_channel_4)
        self.edit_31.setObjectName(u"edit_31")
        self.edit_31.setGeometry(QRect(130, 230, 113, 28))
        self.edit_31.setFont(font2)
        self.edit_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_31.setReadOnly(True)
        self.lbl_32 = QLabel(self.frame_channel_4)
        self.lbl_32.setObjectName(u"lbl_32")
        self.lbl_32.setGeometry(QRect(10, 270, 111, 16))
        self.lbl_32.setFont(font2)
        self.lbl_32.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_33 = QLabel(self.frame_channel_4)
        self.lbl_33.setObjectName(u"lbl_33")
        self.lbl_33.setGeometry(QRect(10, 340, 111, 16))
        self.lbl_33.setFont(font2)
        self.lbl_33.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_32 = QLineEdit(self.frame_channel_4)
        self.edit_32.setObjectName(u"edit_32")
        self.edit_32.setGeometry(QRect(130, 370, 113, 28))
        self.edit_32.setFont(font2)
        self.edit_32.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_32.setReadOnly(True)
        self.edit_33 = QLineEdit(self.frame_channel_4)
        self.edit_33.setObjectName(u"edit_33")
        self.edit_33.setGeometry(QRect(130, 406, 113, 28))
        self.edit_33.setFont(font2)
        self.edit_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_33.setReadOnly(True)
        self.edit_34 = QLineEdit(self.frame_channel_4)
        self.edit_34.setObjectName(u"edit_34")
        self.edit_34.setGeometry(QRect(130, 266, 113, 28))
        self.edit_34.setFont(font2)
        self.edit_34.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_34.setReadOnly(True)
        self.lbl_34 = QLabel(self.frame_channel_4)
        self.lbl_34.setObjectName(u"lbl_34")
        self.lbl_34.setGeometry(QRect(10, 410, 111, 16))
        self.lbl_34.setFont(font2)
        self.lbl_34.setStyleSheet(u"")
        self.lbl_34.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_35 = QLabel(self.frame_channel_4)
        self.lbl_35.setObjectName(u"lbl_35")
        self.lbl_35.setGeometry(QRect(10, 374, 111, 16))
        self.lbl_35.setFont(font2)
        self.lbl_35.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.lbl_36 = QLabel(self.frame_channel_4)
        self.lbl_36.setObjectName(u"lbl_36")
        self.lbl_36.setGeometry(QRect(10, 444, 111, 16))
        self.lbl_36.setFont(font2)
        self.lbl_36.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_35 = QLineEdit(self.frame_channel_4)
        self.edit_35.setObjectName(u"edit_35")
        self.edit_35.setGeometry(QRect(130, 336, 113, 28))
        self.edit_35.setFont(font2)
        self.edit_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_35.setReadOnly(True)
        self.lbl_37 = QLabel(self.frame_channel_4)
        self.lbl_37.setObjectName(u"lbl_37")
        self.lbl_37.setGeometry(QRect(10, 304, 111, 16))
        self.lbl_37.setFont(font2)
        self.lbl_37.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.edit_36 = QLineEdit(self.frame_channel_4)
        self.edit_36.setObjectName(u"edit_36")
        self.edit_36.setGeometry(QRect(130, 300, 113, 28))
        self.edit_36.setFont(font2)
        self.edit_36.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_36.setReadOnly(True)
        self.edit_37 = QLineEdit(self.frame_channel_4)
        self.edit_37.setObjectName(u"edit_37")
        self.edit_37.setGeometry(QRect(130, 440, 113, 28))
        self.edit_37.setFont(font2)
        self.edit_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.edit_37.setReadOnly(True)
        self.btn_start_test_4 = QPushButton(self.frame_channel_4)
        self.btn_start_test_4.setObjectName(u"btn_start_test_4")
        self.btn_start_test_4.setEnabled(False)
        self.btn_start_test_4.setGeometry(QRect(20, 480, 231, 31))
        self.btn_start_test_4.setFont(font3)
        self.btn_start_test_4.setIcon(icon1)
        self.tbtn_settings_channel_4 = QToolButton(self.frame_channel_4)
        self.tbtn_settings_channel_4.setObjectName(u"tbtn_settings_channel_4")
        self.tbtn_settings_channel_4.setGeometry(QRect(230, 10, 31, 31))
        self.tbtn_settings_channel_4.setIcon(icon2)
        self.lbl_ico_channel_4 = QLabel(self.frame_channel_4)
        self.lbl_ico_channel_4.setObjectName(u"lbl_ico_channel_4")
        self.lbl_ico_channel_4.setGeometry(QRect(6, 6, 41, 41))
        self.lbl_ico_channel_4.setFont(font1)
        self.lbl_ico_channel_4.setAutoFillBackground(False)
        self.lbl_ico_channel_4.setStyleSheet(u"")
        self.lbl_ico_channel_4.setFrameShape(QFrame.Shape.NoFrame)
        self.lbl_ico_channel_4.setFrameShadow(QFrame.Shadow.Plain)
        self.lbl_ico_channel_4.setTextFormat(Qt.TextFormat.AutoText)
        self.lbl_ico_channel_4.setPixmap(QPixmap(u":/ICO/N4_36.png"))
        self.lbl_ico_channel_4.setScaledContents(False)
        self.lbl_ico_channel_4.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.lbl_ico_channel_4.setOpenExternalLinks(False)
        self.lbl_ico_channel_4.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)
        self.frm_back_ch_4 = QFrame(self.frame_channel_4)
        self.frm_back_ch_4.setObjectName(u"frm_back_ch_4")
        self.frm_back_ch_4.setGeometry(QRect(2, 2, 266, 48))
        self.frm_back_ch_4.setFrameShape(QFrame.Shape.Panel)
        self.frm_back_ch_4.setFrameShadow(QFrame.Shadow.Plain)
        self.frm_back_ch_4.raise_()
        self.lbl_status_channel_4.raise_()
        self.lbl_26.raise_()
        self.edit_26.raise_()
        self.lbl_28.raise_()
        self.edit_28.raise_()
        self.lbl_29.raise_()
        self.edit_29.raise_()
        self.lbl_30.raise_()
        self.edit_30.raise_()
        self.lbl_31.raise_()
        self.edit_31.raise_()
        self.lbl_32.raise_()
        self.lbl_33.raise_()
        self.edit_32.raise_()
        self.edit_33.raise_()
        self.edit_34.raise_()
        self.lbl_34.raise_()
        self.lbl_35.raise_()
        self.lbl_36.raise_()
        self.edit_35.raise_()
        self.lbl_37.raise_()
        self.edit_36.raise_()
        self.edit_37.raise_()
        self.btn_start_test_4.raise_()
        self.tbtn_settings_channel_4.raise_()
        self.lbl_ico_channel_4.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        self.statusBar.setToolTipDuration(-1)
        self.statusBar.setSizeGripEnabled(False)
        MainWindow.setStatusBar(self.statusBar)
#if QT_CONFIG(shortcut)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.btn_connect, self.tbtn_settings_channel_1)
        QWidget.setTabOrder(self.tbtn_settings_channel_1, self.edit_001)
        QWidget.setTabOrder(self.edit_001, self.edit_2)
        QWidget.setTabOrder(self.edit_2, self.edit_14)
        QWidget.setTabOrder(self.edit_14, self.edit_26)
        QWidget.setTabOrder(self.edit_26, self.btn_logs)
        QWidget.setTabOrder(self.btn_logs, self.edit_009)
        QWidget.setTabOrder(self.edit_009, self.edit_004)
        QWidget.setTabOrder(self.edit_004, self.edit_005)
        QWidget.setTabOrder(self.edit_005, self.edit_006)
        QWidget.setTabOrder(self.edit_006, self.btn_start_test)
        QWidget.setTabOrder(self.btn_start_test, self.edit_012)
        QWidget.setTabOrder(self.edit_012, self.edit_010)
        QWidget.setTabOrder(self.edit_010, self.list_com)
        QWidget.setTabOrder(self.list_com, self.tbtn_settings_com)
        QWidget.setTabOrder(self.tbtn_settings_com, self.edit_008)
        QWidget.setTabOrder(self.edit_008, self.edit_4)
        QWidget.setTabOrder(self.edit_4, self.edit_003)
        QWidget.setTabOrder(self.edit_003, self.edit_5)
        QWidget.setTabOrder(self.edit_5, self.edit_6)
        QWidget.setTabOrder(self.edit_6, self.edit_7)
        QWidget.setTabOrder(self.edit_7, self.edit_11)
        QWidget.setTabOrder(self.edit_11, self.edit_12)
        QWidget.setTabOrder(self.edit_12, self.edit_8)
        QWidget.setTabOrder(self.edit_8, self.edit_10)
        QWidget.setTabOrder(self.edit_10, self.edit_9)
        QWidget.setTabOrder(self.edit_9, self.edit_13)
        QWidget.setTabOrder(self.edit_13, self.btn_start_test_2)
        QWidget.setTabOrder(self.btn_start_test_2, self.tbtn_settings_channel_2)
        QWidget.setTabOrder(self.tbtn_settings_channel_2, self.edit_011)
        QWidget.setTabOrder(self.edit_011, self.edit_16)
        QWidget.setTabOrder(self.edit_16, self.edit_17)
        QWidget.setTabOrder(self.edit_17, self.edit_18)
        QWidget.setTabOrder(self.edit_18, self.edit_19)
        QWidget.setTabOrder(self.edit_19, self.edit_20)
        QWidget.setTabOrder(self.edit_20, self.edit_21)
        QWidget.setTabOrder(self.edit_21, self.edit_22)
        QWidget.setTabOrder(self.edit_22, self.edit_23)
        QWidget.setTabOrder(self.edit_23, self.edit_24)
        QWidget.setTabOrder(self.edit_24, self.edit_25)
        QWidget.setTabOrder(self.edit_25, self.btn_start_test_3)
        QWidget.setTabOrder(self.btn_start_test_3, self.tbtn_settings_channel_3)
        QWidget.setTabOrder(self.tbtn_settings_channel_3, self.edit_28)
        QWidget.setTabOrder(self.edit_28, self.edit_007)
        QWidget.setTabOrder(self.edit_007, self.edit_29)
        QWidget.setTabOrder(self.edit_29, self.edit_30)
        QWidget.setTabOrder(self.edit_30, self.edit_31)
        QWidget.setTabOrder(self.edit_31, self.edit_32)
        QWidget.setTabOrder(self.edit_32, self.edit_33)
        QWidget.setTabOrder(self.edit_33, self.edit_34)
        QWidget.setTabOrder(self.edit_34, self.edit_35)
        QWidget.setTabOrder(self.edit_35, self.edit_36)
        QWidget.setTabOrder(self.edit_36, self.edit_37)
        QWidget.setTabOrder(self.edit_37, self.btn_start_test_4)
        QWidget.setTabOrder(self.btn_start_test_4, self.tbtn_settings_channel_4)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u0441\u0442 \u0430\u043a\u043a\u0443\u043c\u0443\u043b\u044f\u0442\u043e\u0440\u043e\u0432.", None))
        self.lbl_ico_channel_1.setText("")
        self.lbl_001.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u043c\u0435\u0440 \u0410\u041a\u0411", None))
        self.edit_001.setText(QCoreApplication.translate("MainWindow", u"AKB-0000", None))
        self.lbl_003.setText(QCoreApplication.translate("MainWindow", u"U \u043d\u0430\u0447", None))
        self.edit_003.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_004.setText(QCoreApplication.translate("MainWindow", u"U \u0442\u0435\u043a", None))
        self.edit_004.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_005.setText(QCoreApplication.translate("MainWindow", u"I \u0442\u0435\u043a", None))
        self.edit_005.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_006.setText(QCoreApplication.translate("MainWindow", u"P \u0442\u0435\u043a", None))
        self.edit_006.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_007.setText(QCoreApplication.translate("MainWindow", u"C \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_009.setText(QCoreApplication.translate("MainWindow", u"C \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.edit_010.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_011.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_007.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_011.setText(QCoreApplication.translate("MainWindow", u"C \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_010.setText(QCoreApplication.translate("MainWindow", u"W \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.lbl_012.setText(QCoreApplication.translate("MainWindow", u"W \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_009.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_008.setText(QCoreApplication.translate("MainWindow", u"W \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_008.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_012.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.btn_start_test.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u0443\u0441\u043a \u0442\u0435\u0441\u0442\u0430", None))
#if QT_CONFIG(tooltip)
        self.tbtn_settings_channel_1.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbtn_settings_channel_1.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043a\u0430\u043d\u0430\u043b\u0430 1", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_settings_channel_1.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_satus_channel_1.setText(QCoreApplication.translate("MainWindow", u"\u041f\u041e\u0414\u041a\u041b\u042e\u0427\u0415\u041d", None))
#if QT_CONFIG(statustip)
        self.btn_connect.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u043a\u043b\u044e\u0447\u0438\u0442\u044c\u0441\u044f \u043a \u0441\u0438\u0441\u0442\u0435\u043c\u0435 \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f", None))
#endif // QT_CONFIG(statustip)
        self.btn_connect.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0434\u043a\u043b\u044e\u0447\u0438\u0442\u044c\u0441\u044f", None))
        self.lbl_messages.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0436\u0438\u0434\u0430\u043d\u0438\u0435 \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u044f \u043a \u0441\u0438\u0441\u0442\u0435\u043c\u0435 \u0442\u0435\u0441\u0442\u0438\u0440\u043e\u0432\u0430\u043d\u0438\u044f \u0430\u043a\u043a\u0443\u043c\u0443\u043b\u044f\u0442\u043e\u0440\u043e\u0432...", None))
        self.lbl_error.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0448\u0438\u0431\u043a\u0438: 0", None))
#if QT_CONFIG(statustip)
        self.btn_logs.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043b\u043e\u0433\u043e\u0432 \u0438 \u043f\u043e\u0441\u0442\u0440\u043e\u0435\u043d\u0438\u0435 \u0433\u0440\u0430\u0444\u0438\u043a\u043e\u0432", None))
#endif // QT_CONFIG(statustip)
        self.btn_logs.setText(QCoreApplication.translate("MainWindow", u"\u041f\u0440\u043e\u0441\u043c\u043e\u0442\u0440 \u043b\u043e\u0433\u043e\u0432", None))
        self.lbl_com_ports.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u0440\u0442:", None))
#if QT_CONFIG(statustip)
        self.list_com.setStatusTip(QCoreApplication.translate("MainWindow", u"\u0412\u044b\u0431\u043e\u0440 COM-\u043f\u043e\u0440\u0442\u0430", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.tbtn_settings_com.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043f\u043e\u0440\u0442\u0430", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_settings_com.setText("")
        self.lbl_status_channel_2.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0415 \u041f\u041e\u0414\u041a\u041b\u042e\u0427\u0415\u041d", None))
        self.lbl_2.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u043c\u0435\u0440 \u0410\u041a\u0411", None))
        self.edit_2.setText(QCoreApplication.translate("MainWindow", u"AKB-0000", None))
        self.lbl_4.setText(QCoreApplication.translate("MainWindow", u"U \u043d\u0430\u0447", None))
        self.edit_4.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_5.setText(QCoreApplication.translate("MainWindow", u"U \u0442\u0435\u043a", None))
        self.edit_5.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_6.setText(QCoreApplication.translate("MainWindow", u"I \u0442\u0435\u043a", None))
        self.edit_6.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_7.setText(QCoreApplication.translate("MainWindow", u"P \u0442\u0435\u043a", None))
        self.edit_7.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_8.setText(QCoreApplication.translate("MainWindow", u"C \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_10.setText(QCoreApplication.translate("MainWindow", u"C \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.edit_11.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_12.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_8.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_12.setText(QCoreApplication.translate("MainWindow", u"C \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_11.setText(QCoreApplication.translate("MainWindow", u"W \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.lbl_13.setText(QCoreApplication.translate("MainWindow", u"W \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_10.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_9.setText(QCoreApplication.translate("MainWindow", u"W \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_9.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_13.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.btn_start_test_2.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u0443\u0441\u043a \u0442\u0435\u0441\u0442\u0430", None))
#if QT_CONFIG(tooltip)
        self.tbtn_settings_channel_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbtn_settings_channel_2.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043a\u0430\u043d\u0430\u043b\u0430 2", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_settings_channel_2.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_ico_channel_2.setText("")
        self.lbl_satus_channel_3.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0415 \u041f\u041e\u0414\u041a\u041b\u042e\u0427\u0415\u041d", None))
        self.lbl_14.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u043c\u0435\u0440 \u0410\u041a\u0411", None))
        self.edit_14.setText(QCoreApplication.translate("MainWindow", u"AKB-0000", None))
        self.lbl_16.setText(QCoreApplication.translate("MainWindow", u"U \u043d\u0430\u0447", None))
        self.edit_16.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_17.setText(QCoreApplication.translate("MainWindow", u"U \u0442\u0435\u043a", None))
        self.edit_17.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_18.setText(QCoreApplication.translate("MainWindow", u"I \u0442\u0435\u043a", None))
        self.edit_18.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_19.setText(QCoreApplication.translate("MainWindow", u"P \u0442\u0435\u043a", None))
        self.edit_19.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_20.setText(QCoreApplication.translate("MainWindow", u"C \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_21.setText(QCoreApplication.translate("MainWindow", u"C \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.edit_20.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_21.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_22.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_22.setText(QCoreApplication.translate("MainWindow", u"C \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_23.setText(QCoreApplication.translate("MainWindow", u"W \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.lbl_24.setText(QCoreApplication.translate("MainWindow", u"W \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_23.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_25.setText(QCoreApplication.translate("MainWindow", u"W \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_24.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_25.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.btn_start_test_3.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u0443\u0441\u043a \u0442\u0435\u0441\u0442\u0430", None))
#if QT_CONFIG(tooltip)
        self.tbtn_settings_channel_3.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbtn_settings_channel_3.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043a\u0430\u043d\u0430\u043b\u0430 3", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_settings_channel_3.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_ico_channel_3.setText("")
        self.lbl_status_channel_4.setText(QCoreApplication.translate("MainWindow", u"\u041d\u0415 \u041f\u041e\u0414\u041a\u041b\u042e\u0427\u0415\u041d", None))
        self.lbl_26.setText(QCoreApplication.translate("MainWindow", u"\u041d\u043e\u043c\u0435\u0440 \u0410\u041a\u0411", None))
        self.edit_26.setText(QCoreApplication.translate("MainWindow", u"AKB-0000", None))
        self.lbl_28.setText(QCoreApplication.translate("MainWindow", u"U \u043d\u0430\u0447", None))
        self.edit_28.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_29.setText(QCoreApplication.translate("MainWindow", u"U \u0442\u0435\u043a", None))
        self.edit_29.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_30.setText(QCoreApplication.translate("MainWindow", u"I \u0442\u0435\u043a", None))
        self.edit_30.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_31.setText(QCoreApplication.translate("MainWindow", u"P \u0442\u0435\u043a", None))
        self.edit_31.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_32.setText(QCoreApplication.translate("MainWindow", u"C \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_33.setText(QCoreApplication.translate("MainWindow", u"C \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.edit_32.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_33.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_34.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_34.setText(QCoreApplication.translate("MainWindow", u"C \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.lbl_35.setText(QCoreApplication.translate("MainWindow", u"W \u0440\u0430\u0437\u0440\u044f\u0434\u0430", None))
        self.lbl_36.setText(QCoreApplication.translate("MainWindow", u"W \u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_35.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.lbl_37.setText(QCoreApplication.translate("MainWindow", u"W \u043f\u043e\u0434\u0437\u0430\u0440\u044f\u0434\u0430", None))
        self.edit_36.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.edit_37.setText(QCoreApplication.translate("MainWindow", u"00.000", None))
        self.btn_start_test_4.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u043f\u0443\u0441\u043a \u0442\u0435\u0441\u0442\u0430", None))
#if QT_CONFIG(tooltip)
        self.tbtn_settings_channel_4.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.tbtn_settings_channel_4.setStatusTip(QCoreApplication.translate("MainWindow", u"\u041d\u0430\u0441\u0442\u0440\u043e\u0439\u043a\u0438 \u043a\u0430\u043d\u0430\u043b\u0430 4", None))
#endif // QT_CONFIG(statustip)
        self.tbtn_settings_channel_4.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.lbl_ico_channel_4.setText("")
#if QT_CONFIG(statustip)
        self.statusBar.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.statusBar.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
    # retranslateUi

